import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

// Import font within the component scope
const poppins = localFont({ src: './poppins/Poppins-Medium.ttf' });

export const metadata: Metadata = {
  title: "Mw Products",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
