import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: "Mw Products",
  description: "Generated by create next app",
};


// Font files can be colocated inside of `pages`
export const poppins = localFont({ src: './poppins/Poppins-Medium.ttf' })


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        {children}
      </body>
    </html>
  );
}
